version: "3"
services:
  develop:
    build: .
    ports:
      - "35733:35730"
    container_name: fire-summary-stats-develop
    environment:
      ENVIRONMENT: dev
      DEBUG: "True"
      API_VERSION: v1
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
      AWS_CLOUD_WATCH_LOGGING_ENABLED: "False"
    command: develop
    volumes:
      - ./fireSummary:/opt/fireSummary/fireSummary
    restart: on-failure
