apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: fires-summary-stats
  name: fires-summary-stats
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: fires-summary-stats
    spec:
      containers:
      - name: fires-summary-stats
        image: vizzuality/fires-summary-stats
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: PORT
            value: "5700"
          - name: ENVIRONMENT
            value: staging
          - name: LOCAL_URL
            value: http://fires-summary-stats.default.svc.cluster.local:5700
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: FIRES_DATASET_ID
            value: f77d9907-c082-443f-a58f-0b26634c4ca3
          - name: GLAD_DATASET_ID
            value: dfba90df-77a3-4c80-8e62-493430cbaf3d

        ports:
          - containerPort: 5700

      restartPolicy: Always
