apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: fires-summary-stats
    app: gfw
  name: fires-summary-stats
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: fires-summary-stats
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
      - name: fires-summary-stats
        image: vizzuality/fires-summary-stats
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.25"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "5700"
          - name: ENVIRONMENT
            value: prod
          - name: LOCAL_URL
            value: http://fires-summary-stats.default.svc.cluster.local:5700
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: FIRES_DATASET_ID
            value: 4145f642-5455-4414-b214-58ad39b83e1e
          - name: GLAD_DATASET_ID
            value: 63e88e53-0a88-416e-9532-fa06f703d435

        ports:
          - containerPort: 5700

      restartPolicy: Always
