apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fires-summary-stats
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: fires-summary-stats
  minReplicas: 3
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
